MoviesCatalog/MoviesCatalog.Web/Models/ActorViewModel.cs
using Microsoft.AspNetCore.Http;
using MoviesCatalog.Data.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MoviesCatalog.Web.Models
{
    public class ActorViewModel
    {
        public int Id { get; set; }

        [Required]
        [MinLength(2)]
        [MaxLength(50)]
        [RegularExpression("[A-Za-z]+", ErrorMessage = "The First Name can contain only letters")]
        public string FirstName { get; set; }

        [Required]
        [MinLength(2)]
        [MaxLength(50)]
        [RegularExpression("[A-Za-z]+", ErrorMessage = "The Last Name can contain only letters")]
        public string LastName { get; set; }

        [MaxLength(500)]
        public string Biography { get; set; }

        public IFormFile ActorPicture { get; set; }

        public string Picture { get; set; }

        public bool CanUserEdit { get; set; }

        public ICollection<MovieViewModel> LastFiveMoviesByActor { get; set; }
    }
}

MoviesCatalog/MoviesCatalog.Web/Areas/Admin/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MoviesCatalog.Data.Models;
using MoviesCatalog.Services.Contracts;
using MoviesCatalog.Web.Mappers.Contracts;
using MoviesCatalog.Web.Models;
using MoviesCatalog.Web.Services.Contracts;
using MoviesCatalog.Web.Utils;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MoviesCatalog.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ActorsController : Controller
    {
        private readonly IActorService actorService;
        private readonly IMovieService movieService;
        private readonly IImageOptimizer optimizer;
        private readonly IViewModelMapper<Actor, ActorViewModel> actorMapper;
        private readonly IViewModelMapper<Movie, MovieViewModel> movieMapper;

        public ActorsController(IActorService actorService,
                                IMovieService movieService,
                                IImageOptimizer optimizer,
                                IViewModelMapper<Actor, ActorViewModel> actorMapper,
                                IViewModelMapper<Movie, MovieViewModel> movieMapper)
        {
            this.actorService = actorService ?? throw new ArgumentNullException(nameof(actorService));
            this.movieService = movieService ?? throw new ArgumentNullException(nameof(movieService));
            this.optimizer = optimizer ?? throw new ArgumentNullException(nameof(optimizer));
            this.actorMapper = actorMapper ?? throw new ArgumentNullException(nameof(actorMapper));
            this.movieMapper = movieMapper ?? throw new ArgumentNullException(nameof(movieMapper));
        }

        [TempData]
        public string StatusMessage { get; set; }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ActorViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                string imageName = null;

                if (model.ActorPicture != null)
                {
                    imageName = optimizer.OptimizeImage(model.ActorPicture, 268, 182);
                }

                var actor = await this.actorService.FindActorByNameAsync(model.FirstName, model.LastName);
                if (actor != null)
                {
                    StatusMessage = string.Format(WebConstants.ActorAlreadyExists, model.FirstName, model.LastName);
                    return RedirectToAction("Create", "Actors");
                }
                    actor = await this.actorService
                                    .CreateActorAsync(model.FirstName, model.LastName, imageName, model.Biography);

                if (actor.FirstName == model.FirstName && actor.LastName == model.LastName 
                    && actor.Picture == imageName && actor.Biography == model.Biography)
                {
                    StatusMessage = string.Format(WebConstants.ActorCreated, model.FirstName, model.LastName);

                }
                  return RedirectToAction("Details", "Actors", new { id = actor.Id });
            }

            catch (ArgumentException ex)
            {
                StatusMessage = ex.Message;
                return RedirectToAction("Create", "Actors");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var actor = await this.actorService.GetActorByIdAsync(id);
            var actorViewModel = this.actorMapper.MapFrom(actor);
            return View(actorViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(ActorViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var actor = await this.actorService.GetActorByIdAsync(model.Id);
                if (actor == null)
                {
                    return NotFound();
                }

                string imageName = null;

                if (model.ActorPicture != null)
                {
                    imageName = optimizer.OptimizeImage(model.ActorPicture, 268, 182);
                }

                if (model.Picture != null)
                {
                    optimizer.DeleteOldImage(model.Picture);
                }

                actor = await this.actorService
                                  .UpdateActorAsync(actor, imageName, model.Biography);

                if (actor.FirstName == model.FirstName && actor.LastName == model.LastName &&
                    actor.Picture == model.Picture && actor.Biography == model.Biography)
                {
                    StatusMessage = string.Format(WebConstants.ActorDetailsUpdated, model.FirstName, model.LastName);
                }
                    return RedirectToAction("Details", "Actors", new { id = actor.Id });
                
            }

            catch (ArgumentException ex)
            {
                StatusMessage = ex.Message;
                return RedirectToAction("Update", "Actors", new { id = model.Id });
            }
        }

        [HttpGet]
        public async Task <IActionResult> AddToMovie(int id)
        {
            var actor = await this.actorService.GetActorByIdAsync(id);
            if (actor == null)
            {
                return NotFound();
            }
            var movies = await this.movieService.ShowAllMoviesOrderedDescByRatingAsync();
            var movieViewModel = movies.Select(this.movieMapper.MapFrom);
            ViewData["ActorId"] = id;
            return View(movieViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToMovie(int movieId, int actorId)
        {
            try
            {
                var movie = await this.movieService.GetMovieByIdAsync(movieId);
                if (movie == null)
                {
                    return NotFound();
                }
                var actor = await this.actorService.GetActorByIdAsync(actorId);
                if (actor == null)
                {
                    return NotFound();
                }

                await this.actorService.AddActorToMovieAsync(movie.Id, actor.Id);
              
                StatusMessage = string.Format(WebConstants.ActorAddedToMovie, actor.FirstName, actor.LastName, movie.Title);

                return RedirectToAction("Details", "Actors", new { id = actorId });
            }
            catch (ArgumentException ex)
            {
                StatusMessage = ex.Message;

                return RedirectToAction("Details", "Actors", new { id = actorId });
            }
        }
    }
}

MoviesCatalog/MoviesCatalog.Web/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using MoviesCatalog.Data.Models;
using MoviesCatalog.Services.Contracts;
using MoviesCatalog.Web.Mappers.Contracts;
using MoviesCatalog.Web.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MoviesCatalog.Web.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorService actorService;
        private readonly IViewModelMapper<Actor, ActorViewModel> actorMapper;
        private readonly IViewModelMapper<Movie, MovieViewModel> movieMapper;

        public ActorsController(IActorService actorService,
                                IViewModelMapper<Actor, ActorViewModel> actorMapper,
                                IViewModelMapper<Movie, MovieViewModel> movieMapper)
        {
            this.actorService = actorService ?? throw new ArgumentNullException(nameof(actorService));
            this.actorMapper = actorMapper ?? throw new ArgumentNullException(nameof(actorMapper));
            this.movieMapper = movieMapper ?? throw new ArgumentNullException(nameof(movieMapper));
        }

        public async Task<IActionResult> Index()
        {
            var actors = await this.actorService.ShowAllActorsAsync();
            var actorViewModel = actors.Select(this.actorMapper.MapFrom).ToList();
            return View(actorViewModel);
        }

        public async Task<IActionResult> ActorsByName(char id)
        {
            var actors = await this.actorService.ShowActorsStartWithSymbolAsync(id);
            var actorViewModel = actors.Select(this.actorMapper.MapFrom).ToList();
            return View(actorViewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var actor = await this.actorService.GetActorByIdAsync(id);

            var actorMovies = await this.actorService.ShowLastFiveActorMoviesAsync(actor.Id);

            var actorViewModel = this.actorMapper.MapFrom(actor);
            actorViewModel.LastFiveMoviesByActor = actorMovies.Select(this.movieMapper.MapFrom).ToList();

            return View(actorViewModel);
        }
    }
}

MoviesCatalog/MoviesCatalog.Web/Controllers/MoviesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MoviesCatalog.Data.Models;
using MoviesCatalog.Services.Contracts;
using MoviesCatalog.Web.Mappers.Contracts;
using MoviesCatalog.Web.Models;

namespace MoviesCatalog.Web.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService movieService;
        private readonly IViewModelMapper<Movie, MovieViewModel> movieViewMapper;
        private readonly IViewModelMapper<Review,ReviewViewModel> reviewViewMapper;
        private readonly IViewModelMapper<Genre, GenreViewModel> genreViewMapper;
        private readonly IViewModelMapper<Actor, ActorViewModel> actorViewMapper;

        public MoviesController(IMovieService movieService,
                                IViewModelMapper<Movie, MovieViewModel> movieViewMapper,
                                IViewModelMapper<Review, ReviewViewModel> reviewViewMapper,
                                IViewModelMapper<Genre,GenreViewModel> genreViewMapper,
                                IViewModelMapper<Actor, ActorViewModel> actorViewMapper)
        {
            this.movieService = movieService ?? throw new ArgumentNullException(nameof(movieService));
            this.movieViewMapper = movieViewMapper ?? throw new ArgumentNullException(nameof(movieViewMapper));
            this.reviewViewMapper = reviewViewMapper ?? throw new ArgumentNullException(nameof(reviewViewMapper));
            this.genreViewMapper = genreViewMapper ?? throw new ArgumentNullException(nameof(genreViewMapper));
            this.actorViewMapper = actorViewMapper ?? throw new ArgumentNullException(nameof(actorViewMapper));
        }      
            
        public async Task<IActionResult> Details(int id)
        {
            var movie = await this.movieService.GetMovieByIdAsync(id);            

            if (movie == null)
            {
                return NotFound();
            }

            var movieLast5Reviews = await this.movieService.LastFiveReviewsByMovieAsync(id);
            var movieAllReviews = await this.movieService.AllReviewsByMovieAsync(id);

            var movieAllGenres = await this.movieService.AllGenresByMovieAsync(id);
            var movieAllActors = await this.movieService.AllActorsByMovieAsync(id);

            var movieViewModel = this.movieViewMapper.MapFrom(movie);

            movieViewModel.LastFiveReviewsByMovie = movieLast5Reviews.Select(this.reviewViewMapper.MapFrom).ToList();
            movieViewModel.AllReviewsByMovie = movieAllReviews.Select(this.reviewViewMapper.MapFrom).ToList();

            movieViewModel.AllGenresByMovie = movieAllGenres.Select(this.genreViewMapper.MapFrom).ToList();
            movieViewModel.AllActorsByMovie = movieAllActors.Select(this.actorViewMapper.MapFrom).ToList();

            return View(movieViewModel);
        }
        
        public async Task<IActionResult> MoviesByName(char id)
        {
            var moviesByStartingSymbol = await this.movieService.ShowMoviesStartWithSymbolAsync(id);

            var movieViewModel = moviesByStartingSymbol.Select(this.movieViewMapper.MapFrom).ToList();            
            
            return View(movieViewModel);
        }

        public async Task<IActionResult> Index()
        {
            var movies = await this.movieService.ShowAllMoviesOrderedDescByRatingAsync();
            var movieViewModel = movies.Select(this.movieViewMapper.MapFrom).ToList();
            return View(movieViewModel);
        }

        public async Task<IActionResult> Search(string searchName)
        {
            var movies = await this.movieService.SearchMoviesContainsStringAsync(searchName);
            var movieViewModel = movies.Select(this.movieViewMapper.MapFrom).ToList();
            return View("IndexSearch",movieViewModel);
        }               
    }
}

MoviesCatalog/MoviesCatalog.Web/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using MoviesCatalog.Data.Models;
using MoviesCatalog.Services.Contracts;
using MoviesCatalog.Web.Mappers.Contracts;
using MoviesCatalog.Web.Models;
using MoviesCatalog.Web.Services.Contracts;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MoviesCatalog.Web.Controllers
{
    public class UsersController : Controller
    {

        private readonly IUserService userService;
        private readonly IViewModelMapper<ApplicationUser, UserViewModel> userMapper;
        private readonly IImageOptimizer optimizer;
        private readonly IViewModelMapper<Review, ReviewViewModel> reviewMapper;

        public UsersController(IUserService userService,
                               IViewModelMapper<ApplicationUser, UserViewModel> userMapper,
                               IImageOptimizer optimizer,
                               IViewModelMapper<Review, ReviewViewModel> reviewMapper)
        {
            this.userService = userService ?? throw new ArgumentNullException(nameof(userService));
            this.userMapper = userMapper ?? throw new ArgumentNullException(nameof(userMapper));
            this.optimizer = optimizer ?? throw new ArgumentNullException(nameof(optimizer));
            this.reviewMapper = reviewMapper ?? throw new ArgumentNullException(nameof(reviewMapper));
        }

        [TempData] public string StatusMessage { get; set; }

        public async Task<IActionResult> Index()
        {
            var users = await this.userService.ShowAllUsersAsync();

            var userViewModel = users.Select(this.userMapper.MapFrom).ToList();
            return View(userViewModel);
        }

        public async Task<IActionResult> UsersByName(string id)
        {
            var users = await this.userService.ShowUsersStartWithSymbolAsync(id);

            var userViewModel = users.Select(this.userMapper.MapFrom).ToList();
            return View(userViewModel);
        }
    }
}

MoviesCatalog/MoviesCatalog.Web/Views/Shared/_ActorsTable.cshtml
@model IEnumerable<ActorViewModel>

<table id="table" class="table table-striped border border-info">
    <thead>
        <tr>
            <th scope="col">№</th>
            <th scope="col">Picture</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
        </tr>
    </thead>
    <tbody>
        @{
            int counter = 1;
        }
        @foreach (var actor in Model)
        {
            <tr>
                <td>@counter</td>
                @{
                    counter++;
                }
                <td class="w3-list-img"><a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Id"><img src="~/images/@(actor.Picture ?? "noimage.jpg")" /><span></span></a></td>
                <td><a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Id">@actor.FirstName</a></td>
                <td><a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Id">@actor.LastName</a></td>
            </tr>
        }
    </tbody>
</table>

MoviesCatalog/MoviesCatalog.Web/Views/Shared/_ActorsTablePartial.cshtml
@model IEnumerable<ActorViewModel>

<table id="table" class="table table-striped border border-info">
    <thead>
        <tr>
            <th scope="col" width="5%">№</th>
            <th scope="col" width="30%">Picture</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
        </tr>
    </thead>
    <tbody>
        @{
            int counter = 1;
        }
        @foreach (var actor in Model)
        {
        <tr>
            <td>@counter</td>
            @{
                counter++;
            }
            <td class="w3-list-img"><a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Id"><img src="~/images/@(actor.Picture ?? "noimage.jpg")" /><span></span></a></td>
            <td><a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Id">@actor.FirstName</a></td>
            <td><a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Id">@actor.LastName</a></td>
        </tr>
        }
    </tbody>
</table>

MoviesCatalog/MoviesCatalog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoviesCatalog</title>
    <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link rel="stylesheet" href="/css/contactstyle.css" type="text/css" media="all" />
    <link rel="stylesheet" href="/css/faqstyle.css" type="text/css" media="all" />
    <link href="/css/medile.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="/css/news.css" type="text/css" media="all" />
    <link rel="stylesheet" href="/list-css/list.css" type="text/css" media="all" />
    <link href="/css/jquery.slidey.min.css" rel="stylesheet">
    <link href="/css/popuo-box.css" rel="stylesheet" type="text/css" media="all" />
    <link rel="stylesheet" href="/css/font-awesome.min.css" />
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="/css/owl.carousel.css" rel="stylesheet" type="text/css" media="all">
    <link href="~/css/custom.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/css/single.css" rel='stylesheet' type='text/css' />
    <link href='//fonts.googleapis.com/css?family=Roboto+Condensed:400,700italic,700,400italic,300italic,300' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="/js/jquery-2.1.4.min.js"></script>
    <script src="/js/owl.carousel.js"></script>
    <script>
        $(document).ready(function () {
            $("#owl-demo").owlCarousel({

                autoPlay: 3000, //Set AutoPlay to 3 seconds

                items: 5,
                itemsDesktop: [640, 4],
                itemsDesktopSmall: [414, 3]

            });

        });
    </script>

    <script>
        $(document).ready(function () {
            $(".dropdown").hover(
                function () {
                    $('.dropdown-menu', this).stop(true, true).slideDown("fast");
                    $(this).toggleClass('open');
                },
                function () {
                    $('.dropdown-menu', this).stop(true, true).slideUp("fast");
                    $(this).toggleClass('open');
                }
            );
        });
    </script>
    <!-- //banner-bottom-plugin -->
    <link href='//fonts.googleapis.com/css?family=Roboto+Condensed:400,700italic,700,400italic,300italic,300' rel='stylesheet' type='text/css'>
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="/js/move-top.js"></script>
    <script type="text/javascript" src="/js/easing.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
            });
        });
    </script>

</head>
<body>
    <!-- header -->
    <div class="header">
        <div class="container">
            <div class="w3layouts_logo">
                <a href="/home"><h1>Movies<span>Catalog</span></h1></a>
            </div>
            <div class="w3_search">
                <form asp-controller="movies" asp-action="Search" method="get">
                    <input type="text" name="searchName" placeholder="Search Movie" required="">
                    <input type="submit" value="Go">
                </form>
            </div>
            <div class="w3l_sign_in_register">
                <ul>
                    <li>@await Html.PartialAsync("_LoginPartial")</li>
                </ul>

            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <!-- //header -->
    <script>
        $('.toggle').click(function () {
            // Switches the Icon
            $(this).children('i').toggleClass('fa-pencil');
            // Switches the forms
            $('.form').animate({
                height: "toggle",
                'padding-top': 'toggle',
                'padding-bottom': 'toggle',
                opacity: "toggle"
            }, "slow");
        });
    </script>
    <!-- //bootstrap-pop-up -->
    <!-- nav -->
    <div class="movies_nav">
        <div class="container">
            <nav class="navbar navbar-default">
                <div class="navbar-header navbar-left">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
                    <nav>
                        <ul class="nav navbar-nav">
                            <li class="active"><a asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-controller="Genres" asp-action="Index">Genres</a></li>
                            <li><a asp-controller="Movies" asp-action="Index">Movies</a></li>
                            <li><a asp-controller="Actors" asp-action="Index">Actors</a></li>
                            <li><a asp-controller="Users" asp-action="Index">Users</a></li>
                            @if (this.User.IsInRole("Admin"))
                            {
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Add <b class="caret"></b></a>
                                    <ul class="dropdown-menu multi-column columns-3">
                                        <li>
                                            <div class="col-sm-4">
                                                <ul class="multi-column-dropdown">
                                                    <li><a asp-area="Admin" asp-controller="Actors" asp-action="Create">Actor</a></li>
                                                    <li><a asp-area="Admin" asp-controller="Genres" asp-action="Create">Genre</a></li>
                                                    <li><a asp-area="Admin" asp-controller="Movies" asp-action="Create">Movie</a></li>
                                                </ul>
                                            </div>
                                            <div class="clearfix"></div>
                                        </li>
                                    </ul>
                                </li>
                            }
                        </ul>
                    </nav>
                </div>
            </nav>
        </div>
    </div>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    
    <div class="footer">
        <div class="container">
            <div class="w3ls_footer_grid">
                <div class="col-md-6 w3ls_footer_grid_left">
                    <div class="w3ls_footer_grid_left1">
                    </div>
                </div>
                <div class="col-md-6 w3ls_footer_grid_right">
                    <a href="index.html"><h2>Movies<span>Catalog</span></h2></a>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="col-md-5 w3ls_footer_grid1_left">
                <p>&copy; @DateTime.Now.Year Movies Catalog. All rights reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>

            </div>
            <div class="col-md-7 w3ls_footer_grid1_right">
                <ul>
                    <li>
                        <a asp-controller="Movies" asp-action="Index">Movies</a>
                    </li>

                    <li>
                        <a asp-controller="Actors" asp-action="Index">Actors</a>
                    </li>
                    <li>
                        <a asp-controller="Genres" asp-action="Index">Genres</a>
                    </li>
                    <li>
                        <a asp-controller="Users" asp-action="Index">Users</a>
                    </li>
                </ul>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>

    @RenderSection("Scripts", required: false)

</body>
</html>

MoviesCatalog/MoviesCatalog.Web/Views/Shared/_MoviesTablePartial.cshtml
@model IEnumerable<MovieViewModel>

<table id="table" class="table table-striped border border-info">
    <thead>
        <tr>
            <th scope="col" width="5%">№</th>
            <th scope="col" width="30%">Poster</th>
            <th scope="col">Title</th>
            <th scope="col">Average Rating</th>
            <th scope="col">Release Date</th>
            <th scope="col">Uploaded by</th>
            @if (User.Identity.IsAuthenticated)
            {
                <th scope="col">Action</th>
            }
        </tr>
    </thead>
    <tbody>
        @{
            int counter = 1;
        }
        @foreach (var movie in Model)
        {
            <tr>
                <td>@counter</td>
                @{
                    counter++;
                }
                <td class="w3-list-img"><a asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Id"><img src="~/images/@(movie.Poster ?? "noimage.jpg")" /><span></span></a></td>
                <td><a asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Id">@movie.Title</a></td>
                <td>@($"{movie.AverageRating:f1}")</td>
                <td>@movie.ReleaseDate.ToString("MMMM dd, yyyy")</td>
                <td>@movie.UserName</td>
                @if (User.Identity.IsAuthenticated)
                {
                    <td>
                        <a asp-controller="Reviews" asp-action="Create" asp-route-id="@movie.Id" class="btn btn-success"><i class="material-icons">Add Review To Movie</i></a>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/js/jquery/dist/jquery.min.js"></script>
}

MoviesCatalog/MoviesCatalog.Web/Views/Shared/_ReviewsTablePartial.cshtml
@model MovieViewModel

<table id="table" class="table table-striped border border-info">
    <thead>
        <tr>
            <th scope="col" width="5%">№</th>
            <th scope="col" width="30%">Picture</th>
            <th scope="col">Description</th>
            <th scope="col">Username</th>
            @if (User.IsInRole("Admin"))
            {
                <th scope="col">Action</th>
            }
        </tr>
    </thead>
    <tbody>
        @{
            int counter = 1;
        }
        @foreach (var review in Model.AllReviewsByMovie)
        {
            <tr>
                <td>@counter</td>
                @{
                    counter++;
                }
                <td class="w3-list-img"><a asp-controller="Reviews" asp-action="Details" asp-route-id="@review.Id"><img src="~/images/@(Model.Poster ?? "noimage.jpg")" /><span></span></a></td>
                <td>@review.Description</td>
                <td><a asp-controller="Users" asp-action="Details" asp-route-id="@review.UserId">@review.UserName</a></td>
            </tr>
        }
    </tbody>
</table>

MoviesCatalog/MoviesCatalog.Web/Views/Shared/_UsersTablePartial.cshtml
@model IEnumerable<UserViewModel>

<table id="table" class="table table-striped border border-info">
    <thead>
        <tr>
            <th scope="col" width="5%">№</th>
            <th scope="col">Username</th>
            <th scope="col">Reviews</th>
            @if (User.IsInRole("Admin"))
            {
                <th scope="col">Action</th>
            }

        </tr>
    </thead>
    <tbody>
        @{
            int counter = 1;
        }
        @foreach (var user in Model)
        {
        <tr>
            <td>@counter</td>
            @{
                counter++;
            }
           
            <td>@user.UserName</td>
            <td>@user.NumberOfReviews</td>
            @if (User.IsInRole("Admin"))
            {
                <td>
                    <a asp-area="Admin" asp-controller="Users" asp-action="Promote" asp-route-id="@user.Id" class="btn btn-success"><i class="material-icons">Promote</i></a>
                </td>
            }
        </tr>
        }
    </tbody>
</table>