MoviesCatalog/MoviesCatalog.Web/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using MoviesCatalog.Data.Models;
using MoviesCatalog.Services.Contracts;
using MoviesCatalog.Web.Mappers.Contracts;
using MoviesCatalog.Web.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MoviesCatalog.Web.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorService actorService;
        private readonly IViewModelMapper<Actor, ActorViewModel> actorMapper;
        private readonly IViewModelMapper<Movie, MovieViewModel> movieMapper;

        public ActorsController(IActorService actorService,
                                IViewModelMapper<Actor, ActorViewModel> actorMapper,
                                IViewModelMapper<Movie, MovieViewModel> movieMapper)
        {
            this.actorService = actorService ?? throw new ArgumentNullException(nameof(actorService));
            this.actorMapper = actorMapper ?? throw new ArgumentNullException(nameof(actorMapper));
            this.movieMapper = movieMapper ?? throw new ArgumentNullException(nameof(movieMapper));
        }

        public async Task<IActionResult> Index()
        {
            var actors = await this.actorService.ShowAllActorsAsync();
            var actorViewModel = actors.Select(this.actorMapper.MapFrom).ToList();
            return View(actorViewModel);
        }

        public async Task<IActionResult> ActorsByName(char id)
        {
            var actors = await this.actorService.ShowActorsStartWithSymbolAsync(id);
            var actorViewModel = actors.Select(this.actorMapper.MapFrom).ToList();
            return View(actorViewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var actor = await this.actorService.GetActorByIdAsync(id);

            var actorMovies = await this.actorService.ShowLastFiveActorMoviesAsync(actor.Id);

            var actorViewModel = this.actorMapper.MapFrom(actor);
            actorViewModel.LastFiveMoviesByActor = actorMovies.Select(this.movieMapper.MapFrom).ToList();

            return View(actorViewModel);
        }
    }
}

MoviesCatalog/MoviesCatalog.Web/Areas/Admin/Views/Shared/_ActorsTablePartial.cshtml
@model IEnumerable<ActorViewModel>

<table id="table" class="table table-striped border border-info">
    <thead>
        <tr>
            <th scope="col" width="5%">№</th>
            <th scope="col" width="30%">Picture</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            int counter = 1;
        }
        @foreach (var actor in Model)
        {
            <tr>
                <td>@counter</td>
                @{
                    counter++;
                }
                <td class="w3-list-img"><a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Id"><img src="~/images/@(actor.Picture ?? "noimage.jpg")" /><span></span></a></td>
                <td><a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Id">@actor.FirstName</a></td>
                <td><a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Id">@actor.LastName</a></td>
                <td><a asp-area="Admin" asp-action="Movies" asp-controller="AddActor" asp-route-id="@actor.Id" class="btn btn-success"><i class="material-icons">Add Actor To Movie</i></a>
            </tr>
        }
    </tbody>
</table>

MoviesCatalog/MoviesCatalog.Web/Areas/Admin/Views/Shared/_AddActorsToMovieTablePartial.cshtml
@model IEnumerable<ActorViewModel>

<table id="table" class="table table-striped border border-info">
    <thead>
        <tr>
            <th scope="col" width="5%">№</th>
            <th scope="col" width="30%">Picture</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Add To Movie</th>
        </tr>
    </thead>
    <tbody>
        @{
            int counter = 1;
        }
        @foreach (var actor in Model)
        {
        <tr>
            <td>@counter</td>
            @{
                counter++;
            }
            <td class="w3-list-img"><a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Id"><img src="~/images/@(actor.Picture ?? "noimage.jpg")" /><span></span></a></td>
            <td><a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Id">@actor.FirstName</a></td>
            <td><a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Id">@actor.LastName</a></td>

            @if (User.Identity.IsAuthenticated)
            {
                <td>
                    <form asp-area="Admin" asp-controller="Movies" asp-action="AddActorToMovie">
                        <input type="hidden" name="actorId" value="@actor.Id" />
                        <input type="hidden" name="movieId" value="@ViewData["MovieId"]" />
                        <button type="submit" asp-area="Admin" asp-controller="Movies" asp-action="AddActorToMovie" class="btn btn-success"><i class="material-icons">Add Actor To Movie</i></button>
                    </form>
                </td>
            }
        </tr>
        }
    </tbody>
</table>

MoviesCatalog/MoviesCatalog.Web/Areas/Admin/Views/Shared/_MoviesTablePartial.cshtml
@model IEnumerable<MovieViewModel>

<table id="table" class="table table-striped border border-info">
    <thead>
        <tr>
            <th scope="col" width="5%">№</th>
            <th scope="col" width="30%">Poster</th>
            <th scope="col">Title</th>
            <th scope="col">Average Rating</th>
            <th scope="col">Release Date</th>
            <th scope="col">Uploaded by</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            int counter = 1;
        }
        @foreach (var movie in Model)
        {

            <tr>
                <td>@counter</td>
                @{
                    counter++;
                }
                <td class="w3-list-img"><a asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Id"><img src="~/images/@(movie.Poster ?? "noimage.jpg")" /><span></span></a></td>
                <td><a asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Id">@movie.Title</a></td>
                <td>@($"{movie.AverageRating:f1}")</td>
                <td>@movie.ReleaseDate.ToString("MMMM dd, yyyy")</td>
                <td>@movie.UserName</td>
                <td>
                    <form asp-area="Admin" asp-controller="Actors" asp-action="AddToMovie">
                        <input type="hidden" name="movieId" value="@movie.Id" />
                        <input type="hidden" name="actorId" value="@ViewData["ActorId"]" />
                        <button type="submit" asp-area="Admin" asp-controller="Actors" asp-action="AddToMovie" class="btn btn-success"><i class="material-icons">Add Actor To Movie</i></button>
                    </form>
                </td>

            </tr>

        }
    </tbody>
</table>